### ISSUE TITLE
[Doc]  repository setting error

### ISSUE THREAD

**Issue by Borber** [LemonHX/BLAKE3-STD#1]
> Cargo.toml

```toml
[package]
repository = "https://github.com/rustcc/blake3-simd" 
```
is problematic, it does not jump over directly from crates.io. Suggest to change to `https://github.com/LemonHX/BLAKE3-STD`
